### ISSUE TITLE
installation via Composer fails

### ISSUE THREAD

**Issue by inelukipg** [experius/Magento-2-Module-PageNotFound#11] opened 2017-09-25 11:54 UTC
Hi,
Tried to install via composer: 
composer require experius/module-pagenotfound

I get following error:
  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key len
  gth is 767 bytes

I think there is an missing "version" tag in the composer.json file..

**Comment by lewisvoncken** [comment] 2017-09-25 12:00
@inelukipg no version tag in composer is required because versioning is through tags and release of github https://github.com/experius/Magento-2-Module-PageNotFound/releases

I have tried to reproduce the given example but I can't reproduce the error and the module is installed successfully and also successfully executed setup:upgrade

**Comment by inelukipg** [comment] 2017-09-25 12:14
Hi,
I get this error on frontend:

Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Experius_PageNotFound schema: current version - none, required version - 1.0.1
Experius_PageNotFound data: current version - none, required version - 1.0.1

Do you think I can fix this by change in db in table setup_module?

**Comment by lewisvoncken** [comment] 2017-09-25 12:23
@inelukipg 

just run php bin/magento setup:upgrade and the module should work.

**Comment by inelukipg** [comment] 2017-09-25 12:26
When I run php bin/magento setup:upgrade I get this error.

![pagenotfound](https://user-images.githubusercontent.com/23335844/30808235-8ab5033e-a1fd-11e7-8431-424ed442601d.jpg)

**Comment by lewisvoncken** [comment] 2017-09-25 12:29
@inelukipg 

it seems to be a Database Settings Issue on which  we can't help you because we can't reproduce the given error on a fresh installation.

**Comment by inelukipg** [comment] 2017-09-26 09:56
Hi again,
Ok, I managed to fix this and now I'm up and running.
I had to manually add the following to the db table setup_module:

module: Experius_PageNotFound
schema_version: 1.0.1
data_version: 1.0.1

Somehowe this was not done during installation of the module.

Thank you for the help and support!

**Comment by turtlecreations** [comment] 2017-10-02 08:22
Same error here: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes.

I Found this: _Prefix support and lengths of prefixes (where supported) are storage engine dependent. For example, a prefix can be up to 1000 bytes long for MyISAM tables, and 767 bytes for InnoDB tables._ 

This seems to be related to the Storage engine.

**Comment by dheesbeen** [comment] 2017-10-02 10:33
We will try and reproduce this so we can fix it. Thanks voor reporting

**Comment by dheesbeen** [comment] 2017-10-03 10:56
There is a new version. A revert to a previous commit. A pull request that adds a index is the cause of the problem. The duplicate check will be added and fixed in a future version.

**Closed** 2017-11-06 09:48 UTC
